departments = {
    "22 west media",
    "49er shops",
    "academic technology services",
    "alternative spring break",
    "american indian student services program",
    "asi beach pride events",
    "asi communications",
    "asi student assistants and government",
    "asi student recreation and wellness center",
    "asian american pacific islander stuent success initative",
    "asian, pacific islander, & desi resource center",
    "assessment office",
    "associated students, inc.",
    "basic needs program",
    "beach buddies(caps)",
    "beach team",
    "beach wellness",
    "beach xp",
    "beachsync help center",
    "black resource center",
    "black scholars program",
    "bob cole conservatory of music",
    "bob murphy access center",
    "calfresh",
    "california state university, long beach",
    "campus events office",
    "career development office",
    "carolyn campagna kleefeld contemporary art museum",
    "carpenter center",
    "cba graduate students' voices",
    "center for international education",
    "center for successful aging",
    "cla internship program",
    "club sports",
    "cob student center for professional development",
    "coe advising",
    "coe beach engineering student success team (besst)",
    "coe engineering honors track (eht)",
    "coe first year experience",
    "coe office of professional development & internships (opd&i)",
    "coe tutoring",
    "college assistance migrant program",
    "college of business",
    "college of business administration legal information clinic",
    "college of education",
    "college of education student ambassadors",
    "college of education student engagement",
    "college of health & human services",
    "college of liberal arts religious studies",
    "college of natural science & mathematics",
    "college of the arts",
    "counseling and psychological services",
    "csulb alumni",
    "csulb build",
    "csulb intersessions",
    "csulb office of sustainability",
    "dean of students",
    "department of cinematic arts",
    "department of dance",
    "department of theatre arts",
    "departments & services",
    "dig en espanol",
    "dig mag",
    "division of information technology",
    "dream success center",
    "earl burns miller japanese garden",
    "educational opportunity program",
    "financial aid an scholarships office",
    "financial literacy 101",
    "forty-niner student media",
    "fraternity & sorority life",
    "genexcel",
    "graduate center",
    "grow beach",
    "guardian scholars",
    "health professions advising office",
    "housing & residence life",
    "hsi: stem",
    "innovation challenge",
    "institution for innovation and entrepreneurship",
    "interfaith programs",
    "isabel patterson child development center",
    "latinx faculty staf association",
    "laurén chalmers '83 beach pantry",
    "lgbtq resource center",
    "lobby corps",
    "long beach college promise",
    "long beach state athletics",
    "mcnair scholars programs",
    "men's success initative",
    "muslim resource center",
    "nclr/csulb center for latino community health, evaluation and leadership training",
    "not alone at the beach",
    "office of belonging & inclusion",
    "office of equity & compliance",
    "office of student conduct and ethical development",
    "peace corps at csulb",
    "phi kappa phi honor society",
    "president's ambassadors",
    "project resilience",
    "puvunga resource center",
    "rising tides",
    "robert c. maxson student organization center(asi)",
    "safezone ally training",
    "soar connections",
    "student affairs",
    "student health services",
    "student support services program",
    "sustain u",
    "sustainable transportation",
    "test department",
    "the beach transfer transition center",
    "the daily 49er",
    "the learning center",
    "ukelja center for ethical leadership",
    "university honors program",
    "university library",
    "university outreach and school relations",
    "university student union",
    "upward bound program",
    "usu after hours study center (asi)",
    "usu beach balance",
    "usu program council",
    "veterans services",
    "volunteer income tax assistance",
    "women's and gender equity center",
}