# Generated by Django 5.2.4 on 2025-08-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='ext',
            field=models.CharField(default='jpg', max_length=10),
        ),
    ]
