# Generated by Django 5.2.4 on 2025-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0003_rename_images_image_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
