# Generated by Django 5.2.4 on 2025-08-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0004_nodes_aliases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='find_routes.nodes'),
        ),
    ]
