# Generated by Django 5.2.4 on 2025-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0005_remove_nodes_image_image_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='node',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='find_routes.nodes'),
            preserve_default=False,
        ),
    ]
