# Generated by Django 5.2.4 on 2025-08-12 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0006_alter_image_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nodes',
            name='type',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
