# Generated by Django 5.2.4 on 2025-08-12 07:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0007_nodes_coords_nodes_properties_nodes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
