# Generated by Django 5.2.4 on 2025-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_routes', '0008_alter_nodes_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='overview',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
