# fly.toml app configuration file generated for csulbroutes-delicate-night-320 on 2025-08-13T23:24:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'csulbroutes-delicate-night-320'
primary_region = 'lax'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "static_data"
  destination = "/app/staticfiles"

[deploy]
  release_command = "sh -c 'rm -rf /app/staticfiles/* && python manage.py migrate && python manage.py collectstatic --noinput'"
