# Generated by Django 5.2.4 on 2025-08-10 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('find_routes', '0003_rename_images_image_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('starts_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('node_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='find_routes.nodes')),
            ],
        ),
    ]
