# Generated by Django 5.2.4 on 2025-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
