# Generated by Django 5.2.4 on 2025-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_events', '0002_event_org_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarksWithEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_with_events', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
