# Generated by Django 5.2.4 on 2025-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_events', '0003_landmarkswithevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkswithevents',
            name='id',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False),
        ),
    ]
