# Generated by Django 5.2.4 on 2025-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_events', '0004_alter_landmarkswithevents_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_department',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
